### ISSUE TITLE
[BUG] no variant named `CloseRequested` found for enum `RunEvent`

### ISSUE THREAD

**Issue by serg06** [lukethacoder/tauri-react-example#84]
Environment:
- Win11 x64
- rust 1.60.0
- cargo 1.60.0

Steps to reproduce:

- clone the repo
- `yarn`
- `yarn tauri dev` or `yarn tauri build`

Output:

```
   ...
   Compiling tauri-runtime-wry v0.3.5
error[E0599]: no variant named `CloseRequested` found for enum `RunEvent`
   --> src\main.rs:105:15
    |
105 |     RunEvent::CloseRequested { label, api, .. } => {
    |               ^^^^^^^^^^^^^^ variant not found in `RunEvent`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `tauri-react-example` due to previous error
```

Additional notes:
- Looks like `RunEvent::CloseRequested` was [removed in 1.0.0-rc.5](https://tauri.studio/release-notes/)
- It seems like this can be fixed by replacing `RunEvent::CloseRequested { label, api, .. }` with `RunEvent::WindowEvent { label, event: WindowEvent::CloseRequested { api, .. }, .. } => {`

**Comment by lukethacoder** [comment]
@serg06 thanks for the pick up on this one. fixed now.

**Comment by lukethacoder** [comment]
@serg06 thanks for the pick up on this one. fixed now.
